= Coding standards

Submissions to the James project must follow the coding conventions outlined in this
document. James developers are asked to follow coding conventions already present in
the code. (For example, if the existing code has the bracket on the same line as the
`if` statement, then all subsequent code should also follow that convention.) Anything
not explicitly mentioned in this document should adhere to the official
https://www.oracle.com/java/technologies/javase/codeconventions-contents.html[Java Code Conventions].

*Developers who commit code that does not follow the coding conventions outlined in
this document will be responsible for fixing their own code.*

. Spaces between parentheses are optional. The preference is to exclude extra spaces.
Both of these conventions are acceptable:
+
[source,java]
----
if (foo)

or

if ( foo )
----

. Four spaces. *NO tabs*. Period. The James mailing list receives commit messages that
are almost impossible to read if tabs are used.
+
In Emacs-speak, this translates to the following command:
+
----
(setq-default tab-width 4 indent-tabs-mode nil)
----

. Use Unix linefeeds for all `.java` source code files. Only platform-specific files
(e.g. `.bat` files for Windows) should contain non-Unix linefeeds.

. Javadoc *must* exist on all methods. Contributing a missing javadoc for any method,
class, variable, etc., will be GREATLY appreciated as this will help to improve the
James project.

. The Apache License *MUST* be placed at the top of every file.
